---
title: "Visualisation_ggplot"
author: "Shrey Gupta"
date: '2022-04-28'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
install.packages("ggplot2")
install.packages("palmerpenguins")
library("ggplot2")
library("palmerpenguins")
```
## R Markdown Visulisation in R ggplot

This is share of knowledge I hold regarding visualization in R 


```{r }
summary(penguins)

```
```{r }
summary(diamonds)
```
## Scatterplot, Bar Graph, FacetWrap

You can also try plots, for example:

```{r }
ggplot(penguins, aes(flipper_length_mm, body_mass_g )) +geom_point(aes(color= species, shape= species))+geom_smooth()

```

You can also try bar, for example:

```{r }
ggplot(data = diamonds)+ geom_bar(mapping = aes(x=color, fill = cut))
ggplot(data = diamonds)+ geom_bar(mapping = aes(x=cut, fill = clarity))
```


You can also facet wrap, for example:

```{r }
ggplot(penguins, aes(flipper_length_mm, body_mass_g)) +geom_point(aes(color= species))+ facet_wrap(~species)+geom_smooth()

ggplot(data = diamonds)+ geom_bar(mapping = aes(x=color, fill = cut))+ facet_wrap(~cut)

ggplot(penguins, aes(flipper_length_mm, body_mass_g)) +geom_point(aes(color= species))+ facet_grid(sex~species)

```



